(cl:defpackage json_prolog_msgs-srv
  (:use )
  (:export
   "PROLOGNEXTSOLUTION"
   "<PROLOGNEXTSOLUTION-REQUEST>"
   "PROLOGNEXTSOLUTION-REQUEST"
   "<PROLOGNEXTSOLUTION-RESPONSE>"
   "PROLOGNEXTSOLUTION-RESPONSE"
   "PROLOGFINISH"
   "<PROLOGFINISH-REQUEST>"
   "PROLOGFINISH-REQUEST"
   "<PROLOGFINISH-RESPONSE>"
   "PROLOGFINISH-RESPONSE"
   "PROLOGQUERY"
   "<PROLOGQUERY-REQUEST>"
   "PROLOGQUERY-REQUEST"
   "<PROLOGQUERY-RESPONSE>"
   "PROLOGQUERY-RESPONSE"
  ))

