(cl:defpackage iai_kinematics_msgs-srv
  (:use )
  (:export
   "GETWEIGHTEDIK"
   "<GETWEIGHTEDIK-REQUEST>"
   "GETWEIGHTEDIK-REQUEST"
   "<GETWEIGHTEDIK-RESPONSE>"
   "GETWEIGHTEDIK-RESPONSE"
   "GETPOSITIONFK"
   "<GETPOSITIONFK-REQUEST>"
   "GETPOSITIONFK-REQUEST"
   "<GETPOSITIONFK-RESPONSE>"
   "GETPOSITIONFK-RESPONSE"
   "GETPOSITIONIK"
   "<GETPOSITIONIK-REQUEST>"
   "GETPOSITIONIK-REQUEST"
   "<GETPOSITIONIK-RESPONSE>"
   "GETPOSITIONIK-RESPONSE"
   "GETKINEMATICSOLVERINFO"
   "<GETKINEMATICSOLVERINFO-REQUEST>"
   "GETKINEMATICSOLVERINFO-REQUEST"
   "<GETKINEMATICSOLVERINFO-RESPONSE>"
   "GETKINEMATICSOLVERINFO-RESPONSE"
  ))

