(cl:defpackage iai_robosherlock_msgs-srv
  (:use )
  (:export
   "PIZZAPERCEIVEOBJECT"
   "<PIZZAPERCEIVEOBJECT-REQUEST>"
   "PIZZAPERCEIVEOBJECT-REQUEST"
   "<PIZZAPERCEIVEOBJECT-RESPONSE>"
   "PIZZAPERCEIVEOBJECT-RESPONSE"
   "SETRSCONTEXT"
   "<SETRSCONTEXT-REQUEST>"
   "SETRSCONTEXT-REQUEST"
   "<SETRSCONTEXT-RESPONSE>"
   "SETRSCONTEXT-RESPONSE"
   "PERCEIVEOBJECT"
   "<PERCEIVEOBJECT-REQUEST>"
   "PERCEIVEOBJECT-REQUEST"
   "<PERCEIVEOBJECT-RESPONSE>"
   "PERCEIVEOBJECT-RESPONSE"
   "RSQUERYSERVICE"
   "<RSQUERYSERVICE-REQUEST>"
   "RSQUERYSERVICE-REQUEST"
   "<RSQUERYSERVICE-RESPONSE>"
   "RSQUERYSERVICE-RESPONSE"
  ))

