// Generated by gencpp from file knowrob_semantic_map_msgs/GenerateSemanticMapOWLRequest.msg
// DO NOT EDIT!


#ifndef KNOWROB_SEMANTIC_MAP_MSGS_MESSAGE_GENERATESEMANTICMAPOWLREQUEST_H
#define KNOWROB_SEMANTIC_MAP_MSGS_MESSAGE_GENERATESEMANTICMAPOWLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <knowrob_semantic_map_msgs/SemMap.h>

namespace knowrob_semantic_map_msgs
{
template <class ContainerAllocator>
struct GenerateSemanticMapOWLRequest_
{
  typedef GenerateSemanticMapOWLRequest_<ContainerAllocator> Type;

  GenerateSemanticMapOWLRequest_()
    : map()  {
    }
  GenerateSemanticMapOWLRequest_(const ContainerAllocator& _alloc)
    : map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::knowrob_semantic_map_msgs::SemMap_<ContainerAllocator>  _map_type;
  _map_type map;




  typedef boost::shared_ptr< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateSemanticMapOWLRequest_

typedef ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<std::allocator<void> > GenerateSemanticMapOWLRequest;

typedef boost::shared_ptr< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest > GenerateSemanticMapOWLRequestPtr;
typedef boost::shared_ptr< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest const> GenerateSemanticMapOWLRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace knowrob_semantic_map_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'knowrob_semantic_map_msgs': ['/root/catkin_ws/src/knowrob-semantic-map-msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3236e705e162d6ba9e0bfae7b9d0cf43";
  }

  static const char* value(const ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3236e705e162d6baULL;
  static const uint64_t static_value2 = 0x9e0bfae7b9d0cf43ULL;
};

template<class ContainerAllocator>
struct DataType< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "knowrob_semantic_map_msgs/GenerateSemanticMapOWLRequest";
  }

  static const char* value(const ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SemMap map\n\
\n\
================================================================================\n\
MSG: knowrob_semantic_map_msgs/SemMap\n\
# Semantic map message type, Moritz Tenorth, tenorth@cs.tum.edu\n\
# Modifications by Ralf Kaestner, ralf.kaestner@gmail.com\n\
\n\
Header header                             # map timestamp and frame id\n\
\n\
string namespace                          # OWL namespace of the map\n\
string id                                 # unique map identifier\n\
\n\
SemMapPrefix[] prefixes                   # OWL prefixes of the map\n\
string[] imports                          # OWL imports of the map\n\
\n\
SemMapAddress address                     # address of the map\n\
\n\
SemMapObject[] objects                    # list of objects in the map\n\
SemMapAction[] actions                    # list of actions defined on the map\n\
\n\
SemMapObjectProperty[] object_properties  # list of object properties\n\
SemMapDataProperty[] data_properties      # list of data properties\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: knowrob_semantic_map_msgs/SemMapPrefix\n\
# Semantic map prefix message type, Ralf Kaestner, ralf.kaestner@gmail.com\n\
\n\
string name           # prefix name\n\
string prefix         # prefix\n\
\n\
================================================================================\n\
MSG: knowrob_semantic_map_msgs/SemMapAddress\n\
# Semantic map address message type, Ralf Kaestner, ralf.kaestner@gmail.com\n\
\n\
string room_nr         # room number\n\
string floor_nr        # floor number\n\
string street_nr       # street number\n\
string street_name     # street name\n\
string city_name       # city name\n\
\n\
================================================================================\n\
MSG: knowrob_semantic_map_msgs/SemMapObject\n\
# Semantic map object message type, Moritz Tenorth, tenorth@cs.tum.edu\n\
# Modifications by Ralf Kaestner, ralf.kaestner@gmail.com\n\
\n\
Header header               # object timestamp and frame id\n\
\n\
string id                   # unique object identifier\n\
string type                 # object class\n\
\n\
SemMapObjectSize size       # object size\n\
geometry_msgs/Pose pose     # object pose\n\
\n\
string part_of              # identifier of the parent object\n\
\n\
================================================================================\n\
MSG: knowrob_semantic_map_msgs/SemMapObjectSize\n\
# Semantic map object size message type, Ralf Kaestner, ralf.kaestner@gmail.com\n\
\n\
float32 x         # object depth\n\
float32 y         # object width\n\
float32 z         # object height\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: knowrob_semantic_map_msgs/SemMapAction\n\
# Semantic map action message type, Ralf Kaestner, ralf.kaestner@gmail.com\n\
\n\
int8 INTERSECTION_OF = 0    # logic conjunction (and)\n\
int8 UNION_OF = 1           # logic disjunction (or)\n\
\n\
string id                   # unique action class identifier\n\
string type                 # action superclass\n\
bool asserted               # if true, this action is asserted\n\
\n\
string object_acted_on      # identifier of the object acted on\n\
\n\
string[] subactions         # identifiers of the subactions of this action\n\
int8 quantification         # logic quantification of subactions as given above\n\
bool unordered              # if true, subactions of this actions are unordered\n\
\n\
================================================================================\n\
MSG: knowrob_semantic_map_msgs/SemMapObjectProperty\n\
# Semantic map object property message type, Ralf Kaestner, ralf.kaestner@gmail.com\n\
\n\
string id         # object property identifier\n\
string subject    # object property subject\n\
string object     # object property object\n\
\n\
================================================================================\n\
MSG: knowrob_semantic_map_msgs/SemMapDataProperty\n\
# Semantic map data property message type, Ralf Kaestner, ralf.kaestner@gmail.com\n\
\n\
uint8 VALUE_TYPE_STRING = 0\n\
uint8 VALUE_TYPE_BOOL   = 1\n\
uint8 VALUE_TYPE_FLOAT  = 2\n\
uint8 VALUE_TYPE_INT    = 3\n\
\n\
string id           # data property identifier\n\
string subject      # data property subject\n\
uint8 value_type    # data property value type (as defined above)\n\
string value        # data property value\n\
";
  }

  static const char* value(const ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateSemanticMapOWLRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::knowrob_semantic_map_msgs::GenerateSemanticMapOWLRequest_<ContainerAllocator>& v)
  {
    s << indent << "map: ";
    s << std::endl;
    Printer< ::knowrob_semantic_map_msgs::SemMap_<ContainerAllocator> >::stream(s, indent + "  ", v.map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KNOWROB_SEMANTIC_MAP_MSGS_MESSAGE_GENERATESEMANTICMAPOWLREQUEST_H
