// Generated by gencpp from file knowrob_semantic_map_msgs/GetSemanticMap.msg
// DO NOT EDIT!


#ifndef KNOWROB_SEMANTIC_MAP_MSGS_MESSAGE_GETSEMANTICMAP_H
#define KNOWROB_SEMANTIC_MAP_MSGS_MESSAGE_GETSEMANTICMAP_H

#include <ros/service_traits.h>


#include <knowrob_semantic_map_msgs/GetSemanticMapRequest.h>
#include <knowrob_semantic_map_msgs/GetSemanticMapResponse.h>


namespace knowrob_semantic_map_msgs
{

struct GetSemanticMap
{

typedef GetSemanticMapRequest Request;
typedef GetSemanticMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSemanticMap
} // namespace knowrob_semantic_map_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMap > {
  static const char* value()
  {
    return "3236e705e162d6ba9e0bfae7b9d0cf43";
  }

  static const char* value(const ::knowrob_semantic_map_msgs::GetSemanticMap&) { return value(); }
};

template<>
struct DataType< ::knowrob_semantic_map_msgs::GetSemanticMap > {
  static const char* value()
  {
    return "knowrob_semantic_map_msgs/GetSemanticMap";
  }

  static const char* value(const ::knowrob_semantic_map_msgs::GetSemanticMap&) { return value(); }
};


// service_traits::MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMapRequest> should match 
// service_traits::MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMap > 
template<>
struct MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMap >::value();
  }
  static const char* value(const ::knowrob_semantic_map_msgs::GetSemanticMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::knowrob_semantic_map_msgs::GetSemanticMapRequest> should match 
// service_traits::DataType< ::knowrob_semantic_map_msgs::GetSemanticMap > 
template<>
struct DataType< ::knowrob_semantic_map_msgs::GetSemanticMapRequest>
{
  static const char* value()
  {
    return DataType< ::knowrob_semantic_map_msgs::GetSemanticMap >::value();
  }
  static const char* value(const ::knowrob_semantic_map_msgs::GetSemanticMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMapResponse> should match 
// service_traits::MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMap > 
template<>
struct MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::knowrob_semantic_map_msgs::GetSemanticMap >::value();
  }
  static const char* value(const ::knowrob_semantic_map_msgs::GetSemanticMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::knowrob_semantic_map_msgs::GetSemanticMapResponse> should match 
// service_traits::DataType< ::knowrob_semantic_map_msgs::GetSemanticMap > 
template<>
struct DataType< ::knowrob_semantic_map_msgs::GetSemanticMapResponse>
{
  static const char* value()
  {
    return DataType< ::knowrob_semantic_map_msgs::GetSemanticMap >::value();
  }
  static const char* value(const ::knowrob_semantic_map_msgs::GetSemanticMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KNOWROB_SEMANTIC_MAP_MSGS_MESSAGE_GETSEMANTICMAP_H
