// Generated by gencpp from file iai_robosherlock_msgs/PizzaPerceiveObjectRequest.msg
// DO NOT EDIT!


#ifndef IAI_ROBOSHERLOCK_MSGS_MESSAGE_PIZZAPERCEIVEOBJECTREQUEST_H
#define IAI_ROBOSHERLOCK_MSGS_MESSAGE_PIZZAPERCEIVEOBJECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iai_robosherlock_msgs
{
template <class ContainerAllocator>
struct PizzaPerceiveObjectRequest_
{
  typedef PizzaPerceiveObjectRequest_<ContainerAllocator> Type;

  PizzaPerceiveObjectRequest_()
    : object_name()
    , apply_pos_rot_fixes(false)
    , stick_to_map(false)
    , publish_transform_once(false)  {
    }
  PizzaPerceiveObjectRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , apply_pos_rot_fixes(false)
    , stick_to_map(false)
    , publish_transform_once(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  _object_name_type object_name;

   typedef uint8_t _apply_pos_rot_fixes_type;
  _apply_pos_rot_fixes_type apply_pos_rot_fixes;

   typedef uint8_t _stick_to_map_type;
  _stick_to_map_type stick_to_map;

   typedef uint8_t _publish_transform_once_type;
  _publish_transform_once_type publish_transform_once;




  typedef boost::shared_ptr< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PizzaPerceiveObjectRequest_

typedef ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<std::allocator<void> > PizzaPerceiveObjectRequest;

typedef boost::shared_ptr< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest > PizzaPerceiveObjectRequestPtr;
typedef boost::shared_ptr< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest const> PizzaPerceiveObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iai_robosherlock_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'iai_robosherlock_msgs': ['/root/catkin_ws/src/iai_common_msgs/iai_robosherlock_msgs/msg', '/root/catkin_ws/devel/.private/iai_robosherlock_msgs/share/iai_robosherlock_msgs/msg'], 'designator_integration_msgs': ['/root/catkin_ws/src/iai_common_msgs/designator_integration_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4119a4176f82dcc692648a2c4ebcfb1f";
  }

  static const char* value(const ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4119a4176f82dcc6ULL;
  static const uint64_t static_value2 = 0x92648a2c4ebcfb1fULL;
};

template<class ContainerAllocator>
struct DataType< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iai_robosherlock_msgs/PizzaPerceiveObjectRequest";
  }

  static const char* value(const ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n\
bool apply_pos_rot_fixes\n\
bool stick_to_map\n\
bool publish_transform_once\n\
";
  }

  static const char* value(const ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.apply_pos_rot_fixes);
      stream.next(m.stick_to_map);
      stream.next(m.publish_transform_once);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PizzaPerceiveObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iai_robosherlock_msgs::PizzaPerceiveObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_name);
    s << indent << "apply_pos_rot_fixes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.apply_pos_rot_fixes);
    s << indent << "stick_to_map: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stick_to_map);
    s << indent << "publish_transform_once: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.publish_transform_once);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAI_ROBOSHERLOCK_MSGS_MESSAGE_PIZZAPERCEIVEOBJECTREQUEST_H
