// Generated by gencpp from file iai_robosherlock_msgs/SimplePerceiveObjectActionResult.msg
// DO NOT EDIT!


#ifndef IAI_ROBOSHERLOCK_MSGS_MESSAGE_SIMPLEPERCEIVEOBJECTACTIONRESULT_H
#define IAI_ROBOSHERLOCK_MSGS_MESSAGE_SIMPLEPERCEIVEOBJECTACTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalStatus.h>
#include <iai_robosherlock_msgs/SimplePerceiveObjectResult.h>

namespace iai_robosherlock_msgs
{
template <class ContainerAllocator>
struct SimplePerceiveObjectActionResult_
{
  typedef SimplePerceiveObjectActionResult_<ContainerAllocator> Type;

  SimplePerceiveObjectActionResult_()
    : header()
    , status()
    , result()  {
    }
  SimplePerceiveObjectActionResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalStatus_<ContainerAllocator>  _status_type;
  _status_type status;

   typedef  ::iai_robosherlock_msgs::SimplePerceiveObjectResult_<ContainerAllocator>  _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> const> ConstPtr;

}; // struct SimplePerceiveObjectActionResult_

typedef ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<std::allocator<void> > SimplePerceiveObjectActionResult;

typedef boost::shared_ptr< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult > SimplePerceiveObjectActionResultPtr;
typedef boost::shared_ptr< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult const> SimplePerceiveObjectActionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iai_robosherlock_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'iai_robosherlock_msgs': ['/root/catkin_ws/src/iai_common_msgs/iai_robosherlock_msgs/msg', '/root/catkin_ws/devel/.private/iai_robosherlock_msgs/share/iai_robosherlock_msgs/msg'], 'designator_integration_msgs': ['/root/catkin_ws/src/iai_common_msgs/designator_integration_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c321e5be8bfaca730ed42d8a8f82b99";
  }

  static const char* value(const ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c321e5be8bfaca7ULL;
  static const uint64_t static_value2 = 0x30ed42d8a8f82b99ULL;
};

template<class ContainerAllocator>
struct DataType< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iai_robosherlock_msgs/SimplePerceiveObjectActionResult";
  }

  static const char* value(const ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
SimplePerceiveObjectResult result\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: iai_robosherlock_msgs/SimplePerceiveObjectResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# result\n\
#\n\
# upon termination or cancelation, the vision system sends back\n\
# a (potentially incomplete, in case of cancel) list of descriptions\n\
# of objects it has last seen\n\
designator_integration_msgs/Designator[] percepts\n\
\n\
================================================================================\n\
MSG: designator_integration_msgs/Designator\n\
int32 TYPE_OBJECT=0\n\
int32 TYPE_ACTION=1\n\
int32 TYPE_LOCATION=2\n\
int32 TYPE_HUMAN=3\n\
\n\
int32 type\n\
\n\
KeyValuePair[] description\n\
\n\
================================================================================\n\
MSG: designator_integration_msgs/KeyValuePair\n\
# Purely for (de-)serialization purposes\n\
int32 id\n\
int32 parent\n\
\n\
# Data\n\
int32 TYPE_STRING=0\n\
int32 TYPE_FLOAT=1\n\
int32 TYPE_DATA=2\n\
int32 TYPE_LIST=3\n\
int32 TYPE_POSESTAMPED=4\n\
int32 TYPE_POSE=5\n\
int32 TYPE_DESIGNATOR_ACTION=6\n\
int32 TYPE_DESIGNATOR_OBJECT=7\n\
int32 TYPE_DESIGNATOR_LOCATION=8\n\
int32 TYPE_DESIGNATOR_HUMAN=9\n\
int32 TYPE_POINT=10\n\
int32 TYPE_WRENCH=11\n\
int32 TYPE_MATRIX=12\n\
int32 TYPE_VECTOR=13\n\
\n\
int32 type\n\
\n\
string key\n\
string value_string\n\
float64 value_float\n\
char[] value_data\n\
float64[] value_array\n\
geometry_msgs/PoseStamped value_posestamped\n\
geometry_msgs/Pose value_pose\n\
geometry_msgs/Point value_point\n\
geometry_msgs/Wrench value_wrench\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Wrench\n\
# This represents force in free space, separated into\n\
# its linear and angular parts.\n\
Vector3  force\n\
Vector3  torque\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimplePerceiveObjectActionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iai_robosherlock_msgs::SimplePerceiveObjectActionResult_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    s << indent << "result: ";
    s << std::endl;
    Printer< ::iai_robosherlock_msgs::SimplePerceiveObjectResult_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAI_ROBOSHERLOCK_MSGS_MESSAGE_SIMPLEPERCEIVEOBJECTACTIONRESULT_H
