(cl:defpackage knowrob_semantic_map_msgs-srv
  (:use )
  (:export
   "GENERATESEMANTICMAPOWL"
   "<GENERATESEMANTICMAPOWL-REQUEST>"
   "GENERATESEMANTICMAPOWL-REQUEST"
   "<GENERATESEMANTICMAPOWL-RESPONSE>"
   "GENERATESEMANTICMAPOWL-RESPONSE"
   "GETSEMANTICMAP"
   "<GETSEMANTICMAP-REQUEST>"
   "GETSEMANTICMAP-REQUEST"
   "<GETSEMANTICMAP-RESPONSE>"
   "GETSEMANTICMAP-RESPONSE"
  ))

