# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from iai_robosherlock_msgs/PizzaPerceiveObjectRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PizzaPerceiveObjectRequest(genpy.Message):
  _md5sum = "4119a4176f82dcc692648a2c4ebcfb1f"
  _type = "iai_robosherlock_msgs/PizzaPerceiveObjectRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string object_name
bool apply_pos_rot_fixes
bool stick_to_map
bool publish_transform_once
"""
  __slots__ = ['object_name','apply_pos_rot_fixes','stick_to_map','publish_transform_once']
  _slot_types = ['string','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_name,apply_pos_rot_fixes,stick_to_map,publish_transform_once

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PizzaPerceiveObjectRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.object_name is None:
        self.object_name = ''
      if self.apply_pos_rot_fixes is None:
        self.apply_pos_rot_fixes = False
      if self.stick_to_map is None:
        self.stick_to_map = False
      if self.publish_transform_once is None:
        self.publish_transform_once = False
    else:
      self.object_name = ''
      self.apply_pos_rot_fixes = False
      self.stick_to_map = False
      self.publish_transform_once = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3B.pack(_x.apply_pos_rot_fixes, _x.stick_to_map, _x.publish_transform_once))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_name = str[start:end].decode('utf-8')
      else:
        self.object_name = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.apply_pos_rot_fixes, _x.stick_to_map, _x.publish_transform_once,) = _struct_3B.unpack(str[start:end])
      self.apply_pos_rot_fixes = bool(self.apply_pos_rot_fixes)
      self.stick_to_map = bool(self.stick_to_map)
      self.publish_transform_once = bool(self.publish_transform_once)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.object_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3B.pack(_x.apply_pos_rot_fixes, _x.stick_to_map, _x.publish_transform_once))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_name = str[start:end].decode('utf-8')
      else:
        self.object_name = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.apply_pos_rot_fixes, _x.stick_to_map, _x.publish_transform_once,) = _struct_3B.unpack(str[start:end])
      self.apply_pos_rot_fixes = bool(self.apply_pos_rot_fixes)
      self.stick_to_map = bool(self.stick_to_map)
      self.publish_transform_once = bool(self.publish_transform_once)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3B = struct.Struct("<3B")
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from iai_robosherlock_msgs/PizzaPerceiveObjectResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class PizzaPerceiveObjectResponse(genpy.Message):
  _md5sum = "55bca38139826ff27c6f71c5f8ee941c"
  _type = "iai_robosherlock_msgs/PizzaPerceiveObjectResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/TransformStamped object_transf


================================================================================
MSG: geometry_msgs/TransformStamped
# This expresses a transform from coordinate frame header.frame_id
# to the coordinate frame child_frame_id
#
# This message is mostly used by the 
# <a href="http://www.ros.org/wiki/tf">tf</a> package. 
# See its documentation for more information.

Header header
string child_frame_id # the frame id of the child frame
Transform transform

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Transform
# This represents the transform between two coordinate frames in free space.

Vector3 translation
Quaternion rotation

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['object_transf']
  _slot_types = ['geometry_msgs/TransformStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_transf

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PizzaPerceiveObjectResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.object_transf is None:
        self.object_transf = geometry_msgs.msg.TransformStamped()
    else:
      self.object_transf = geometry_msgs.msg.TransformStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.object_transf.header.seq, _x.object_transf.header.stamp.secs, _x.object_transf.header.stamp.nsecs))
      _x = self.object_transf.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.object_transf.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.object_transf.transform.translation.x, _x.object_transf.transform.translation.y, _x.object_transf.transform.translation.z, _x.object_transf.transform.rotation.x, _x.object_transf.transform.rotation.y, _x.object_transf.transform.rotation.z, _x.object_transf.transform.rotation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.object_transf is None:
        self.object_transf = geometry_msgs.msg.TransformStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.object_transf.header.seq, _x.object_transf.header.stamp.secs, _x.object_transf.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_transf.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.object_transf.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_transf.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.object_transf.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.object_transf.transform.translation.x, _x.object_transf.transform.translation.y, _x.object_transf.transform.translation.z, _x.object_transf.transform.rotation.x, _x.object_transf.transform.rotation.y, _x.object_transf.transform.rotation.z, _x.object_transf.transform.rotation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.object_transf.header.seq, _x.object_transf.header.stamp.secs, _x.object_transf.header.stamp.nsecs))
      _x = self.object_transf.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.object_transf.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.object_transf.transform.translation.x, _x.object_transf.transform.translation.y, _x.object_transf.transform.translation.z, _x.object_transf.transform.rotation.x, _x.object_transf.transform.rotation.y, _x.object_transf.transform.rotation.z, _x.object_transf.transform.rotation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.object_transf is None:
        self.object_transf = geometry_msgs.msg.TransformStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.object_transf.header.seq, _x.object_transf.header.stamp.secs, _x.object_transf.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_transf.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.object_transf.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_transf.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.object_transf.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.object_transf.transform.translation.x, _x.object_transf.transform.translation.y, _x.object_transf.transform.translation.z, _x.object_transf.transform.rotation.x, _x.object_transf.transform.rotation.y, _x.object_transf.transform.rotation.z, _x.object_transf.transform.rotation.w,) = _struct_7d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
class PizzaPerceiveObject(object):
  _type          = 'iai_robosherlock_msgs/PizzaPerceiveObject'
  _md5sum = '4790cbbe48b51282b8e13eb7e6b0e95b'
  _request_class  = PizzaPerceiveObjectRequest
  _response_class = PizzaPerceiveObjectResponse
