; Auto-generated. Do not edit!


(cl:in-package iai_robosherlock_msgs-msg)


;//! \htmlinclude HighlightObjectGoal.msg.html

(cl:defclass <HighlightObjectGoal> (roslisp-msg-protocol:ros-message)
  ((obj_name
    :reader obj_name
    :initarg :obj_name
    :type cl:string
    :initform ""))
)

(cl:defclass HighlightObjectGoal (<HighlightObjectGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HighlightObjectGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HighlightObjectGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name iai_robosherlock_msgs-msg:<HighlightObjectGoal> is deprecated: use iai_robosherlock_msgs-msg:HighlightObjectGoal instead.")))

(cl:ensure-generic-function 'obj_name-val :lambda-list '(m))
(cl:defmethod obj_name-val ((m <HighlightObjectGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader iai_robosherlock_msgs-msg:obj_name-val is deprecated.  Use iai_robosherlock_msgs-msg:obj_name instead.")
  (obj_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HighlightObjectGoal>) ostream)
  "Serializes a message object of type '<HighlightObjectGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'obj_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'obj_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HighlightObjectGoal>) istream)
  "Deserializes a message object of type '<HighlightObjectGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'obj_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'obj_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HighlightObjectGoal>)))
  "Returns string type for a message object of type '<HighlightObjectGoal>"
  "iai_robosherlock_msgs/HighlightObjectGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HighlightObjectGoal)))
  "Returns string type for a message object of type 'HighlightObjectGoal"
  "iai_robosherlock_msgs/HighlightObjectGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HighlightObjectGoal>)))
  "Returns md5sum for a message object of type '<HighlightObjectGoal>"
  "a8c7b258e79c151f1035d52dae0a0055")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HighlightObjectGoal)))
  "Returns md5sum for a message object of type 'HighlightObjectGoal"
  "a8c7b258e79c151f1035d52dae0a0055")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HighlightObjectGoal>)))
  "Returns full string definition for message of type '<HighlightObjectGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%~%string obj_name~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HighlightObjectGoal)))
  "Returns full string definition for message of type 'HighlightObjectGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%~%string obj_name~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HighlightObjectGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'obj_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HighlightObjectGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'HighlightObjectGoal
    (cl:cons ':obj_name (obj_name msg))
))
