; Auto-generated. Do not edit!


(cl:in-package iai_robosherlock_msgs-msg)


;//! \htmlinclude HighlightObjectFeedback.msg.html

(cl:defclass <HighlightObjectFeedback> (roslisp-msg-protocol:ros-message)
  ((found
    :reader found
    :initarg :found
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass HighlightObjectFeedback (<HighlightObjectFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <HighlightObjectFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'HighlightObjectFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name iai_robosherlock_msgs-msg:<HighlightObjectFeedback> is deprecated: use iai_robosherlock_msgs-msg:HighlightObjectFeedback instead.")))

(cl:ensure-generic-function 'found-val :lambda-list '(m))
(cl:defmethod found-val ((m <HighlightObjectFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader iai_robosherlock_msgs-msg:found-val is deprecated.  Use iai_robosherlock_msgs-msg:found instead.")
  (found m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <HighlightObjectFeedback>) ostream)
  "Serializes a message object of type '<HighlightObjectFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'found) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <HighlightObjectFeedback>) istream)
  "Deserializes a message object of type '<HighlightObjectFeedback>"
    (cl:setf (cl:slot-value msg 'found) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<HighlightObjectFeedback>)))
  "Returns string type for a message object of type '<HighlightObjectFeedback>"
  "iai_robosherlock_msgs/HighlightObjectFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'HighlightObjectFeedback)))
  "Returns string type for a message object of type 'HighlightObjectFeedback"
  "iai_robosherlock_msgs/HighlightObjectFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<HighlightObjectFeedback>)))
  "Returns md5sum for a message object of type '<HighlightObjectFeedback>"
  "d6c4ae35878abbcf43ece19ba68d70a6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'HighlightObjectFeedback)))
  "Returns md5sum for a message object of type 'HighlightObjectFeedback"
  "d6c4ae35878abbcf43ece19ba68d70a6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<HighlightObjectFeedback>)))
  "Returns full string definition for message of type '<HighlightObjectFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#feedback~%bool found~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'HighlightObjectFeedback)))
  "Returns full string definition for message of type 'HighlightObjectFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#feedback~%bool found~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <HighlightObjectFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <HighlightObjectFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'HighlightObjectFeedback
    (cl:cons ':found (found msg))
))
