(cl:defpackage scanning_table_msgs-msg
  (:use )
  (:export
   "<SCANNING_TABLEACTIONGOAL>"
   "SCANNING_TABLEACTIONGOAL"
   "<SCANNING_TABLEGOAL>"
   "SCANNING_TABLEGOAL"
   "<SCANNING_TABLEACTIONFEEDBACK>"
   "SCANNING_TABLEACTIONFEEDBACK"
   "<SCANNING_TABLEACTION>"
   "SCANNING_TABLEACTION"
   "<SCANNING_TABLERESULT>"
   "SCANNING_TABLERESULT"
   "<SCANNING_TABLEFEEDBACK>"
   "SCANNING_TABLEFEEDBACK"
   "<SCANNING_TABLEACTIONRESULT>"
   "SCANNING_TABLEACTIONRESULT"
  ))

